const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    FORGOT: 'FORGOT',
    LOGOUT: 'LOGOUT',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    GET_CURRENT: "GET_CURRENT",

    GET_PERMISSION: "GET_PERMISSION",
    CREATE_PERMISSION: "CREATE_PERMISSION",
    UPDATE_PERMISSION: "UPDATE_PERMISSION",

    GET_COLOR: "GET_COLOR",
    CREATE_COLOR: "CREATE_COLOR",
    UPDATE_COLOR: "UPDATE_COLOR",

    GET_DIMENSION: "GET_DIMENSION",
    CREATE_DIMENSION: "CREATE_DIMENSION",
    UPDATE_DIMENSION: "UPDATE_DIMENSION",

    GET_ACCOUNT: "GET_ACCOUNT",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    UPDATE_ACCOUNT_ONE: "UPDATE_ACCOUNT_ONE",
    UPDATE_ACCOUNT_BYAD: "UPDATE_ACCOUNT_BYAD",
    UPDATE_ACCOUNT_PASS: "UPDATE_ACCOUNT_PASS",

    GET_MENU: "GET_MENU",
    CREATE_MENU: "CREATE_MENU",
    UPDATE_MENU: "UPDATE_MENU",
    DELETE_MENU: "DELETE_MENU",

    GET_SLIDE: "GET_SLIDE",
    CREATE_SLIDE: "CREATE_SLIDE",
    UPDATE_SLIDE: "UPDATE_SLIDE",
    DELETE_SLIDE: "DELETE_SLIDE",

    GET_STATE: "GET_STATE",
    CREATE_STATE: "CREATE_STATE",
    UPDATE_STATE: "UPDATE_STATE",

    GET_TRANSFER: "GET_TRANSFER",
    CREATE_TRANSFER: "CREATE_TRANSFER",
    UPDATE_TRANSFER: "UPDATE_TRANSFER",
    DELETE_TRANSFER: "DELETE_TRANSFER",

    GET_SAMPLE: "GET_SAMPLE",
    CREATE_SAMPLE: "CREATE_SAMPLE",
    UPDATE_SAMPLE: "UPDATE_SAMPLE",
    GET_AllS_SAMPLE: "GET_AllS_SAMPLE",

    GET_FUNCTION: "GET_FUNCTION",
    CREATE_FUNCTION: "CREATE_FUNCTION",
    UPDATE_FUNCTION: "UPDATE_FUNCTION",
    DELETE_FUNCTION: "DELETE_FUNCTION",
    GET_AllS_FUNCTION: "GET_AllS_FUNCTION",

    GET_ALLOCATION: "GET_ALLOCATION",
    CREATE_ALLOCATION: "CREATE_ALLOCATION",
    UPDATE_ALLOCATION: "UPDATE_ALLOCATION",
    DELETE_ALLOCATION: "DELETE_ALLOCATION",
    GET_AllS_ALLOCATION: "GET_AllS_ALLOCATION",

    GET_TRANSMISSION: "GET_TRANSMISSION",
    CREATE_TRANSMISSION: "CREATE_TRANSMISSION",
    UPDATE_TRANSMISSION: "UPDATE_TRANSMISSION",
    DELETE_TRANSMISSION: "DELETE_TRANSMISSION",
    GET_AllS_TRANSMISSION: "GET_AllS_TRANSMISSION",

    GET_CATEGORIES: "GET_CATEGORIES",
    UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
    CREATE_CATEGORIES: "CREATE_CATEGORIES",

    GET_PRODUCT: "GET_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    CREATE_PRODUCT: "CREATE_PRODUCT",
    GET_PRODUCT_LIMIT: "GET_PRODUCT_LIMIT",

    GET_QUANTITY: "GET_QUANTITY",
    UPDATE_QUANTITY: "UPDATE_QUANTITY",
    CREATE_QUANTITY: "CREATE_QUANTITY",

    GET_IMAGE: "GET_IMAGE",
    UPDATE_IMAGE: "UPDATE_IMAGE",
    CREATE_IMAGE: "CREATE_IMAGE",

    GET_LIKE: "GET_LIKE",
    CREATE_LIKE: "CREATE_LIKE",
    DELETE_LIKE: "DELETE_LIKE",

    GET_INVOICE: "GET_INVOICE",
    CREATE_INVOICE: "CREATE_INVOICE",
    UPDATE_INVOICE: "UPDATE_INVOICE",
    GET_COUNT_INVOICE: "GET_COUNT_INVOICE",
}

export default actionTypes;