const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    FORGOT: 'FORGOT',
    LOGOUT: 'LOGOUT',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    GET_CURRENT: "GET_CURRENT",

    GET_MENU: "GET_MENU",
    CREATE_MENU: "CREATE_MENU",
    UPDATE_MENU: "UPDATE_MENU",
    DELETE_MENU: "DELETE_MENU",

    GET_TRANSFER: "GET_TRANSFER",
    CREATE_TRANSFER: "CREATE_TRANSFER",
    UPDATE_TRANSFER: "UPDATE_TRANSFER",
    DELETE_TRANSFER: "DELETE_TRANSFER",

    GET_CATEGORIES: "GET_CATEGORIES",
    UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
    CREATE_CATEGORIES: "CREATE_CATEGORIES",
}

export default actionTypes;